language: dart
branches:
  only:
    - master
    - /^(?i:release)-.+$/
dart:
  - stable
  - "2.12.0"
dart_task:
  - test: --platform vm
  - test: --platform chrome
  - dartanalyzer: example lib test
  - dartfmt: true
