name: public_suffix
description: A domain parser based on the Public Suffix List, for identifying the root and suffix/TLD of URLs.
version: 3.0.0
homepage: https://www.github.com/komposten/
repository: https://www.github.com/komposten/public_suffix
issue_tracker: https://www.github.com/komposten/public_suffix/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  punycode: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
